{% set name = "veg2hab" %}
{% set version = "1.1.2a1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/veg2hab-{{ version }}.tar.gz
  sha256: 5d3f9ac64a0ff4cd4118dba6b510a82a047e1322beb8fa9922b487ca79e6c27f

build:
  entry_points:
    - veg2hab = veg2hab.__main__:veg2hab
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core 1.9.1
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pandas >=2.2.3,<3.0.0
    - geopandas >=1.0.1,<2.0.0
    - openpyxl >=3.1.2,<4.0.0
    - xlrd >=2.0.1,<3.0.0
    - pyodbc >=5.0.1,<6.0.0
    - pydantic >=2.4.2,<3.0.0
    - setuptools >=75.8.0,<76.0.0
    - click >=8.1.7,<9.0.0
    - fiona >=1.10.0,<2.0.0
    - shapely >=2.0.7,<3.0.0
    - pydantic-settings >=2.2.1,<3.0.0

test:
  imports:
    - veg2hab
  commands:
    - pip check
    - veg2hab --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Spheer-ai/veg2hab
  summary: Package voor automatisch omzetten van vegetatiekarteringen naar habitatkaarten
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.md


extra:
  recipe-maintainers:
    - mark-boer
    - JRdeLange
