{% set name = "veg2hab" %}
{% set version = "1.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/veg2hab-{{ version }}.tar.gz
  sha256: ee32b732a54a8595e6bcc226f7f31afe235d34d1aa20d6e37bbf24ccd6e275fc

build:
  entry_points:
    - veg2hab = veg2hab.__main__:veg2hab
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core 1.9.1
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pandas >=2.2.3,<3.0.0
    - geopandas >=1.0.1,<2.0.0
    - openpyxl >=3.1.5,<4.0.0
    - xlrd >=2.0.1,<3.0.0
    - pyodbc >=5.2.0,<6.0.0
    - pydantic >=2.10.6,<3.0.0
    - setuptools >=75.8.0,<76.0.0
    - click >=8.1.8,<9.0.0
    - fiona >=1.10.1,<2.0.0
    - shapely >=2.0.7,<3.0.0
    - pydantic-settings >=2.8.0,<3.0.0

test:
  imports:
    - veg2hab
  commands:
    - pip check
    - veg2hab --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Spheer-ai/veg2hab
  summary: Package voor automatisch omzetten van vegetatiekarteringen naar habitatkaarten
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.md


extra:
  recipe-maintainers:
    - mark-boer
    - JRdeLange
